# Generated by Django 5.2.16 on 2026-07-23 06:59

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('domains', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text="Email domains associated with this firm, e.g. ['jpmorgan.com'].", size=None)),
                ('regions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('tracks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('sponsors', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(blank=True, default='active', max_length=32)),
            ],
            options={
                'db_table': 'firms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector', models.CharField(max_length=128)),
                ('started', models.DateTimeField()),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='running', max_length=32)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'scrape_runs',
                'ordering': ['-started'],
            },
        ),
        migrations.CreateModel(
            name='EmailPatternStats',
            fields=[
                ('firm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='email_pattern_stats', serialize=False, to='directory.firm')),
                ('delivered', models.PositiveIntegerField(default=0)),
                ('bounced', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'email_pattern_stats',
            },
        ),
        migrations.CreateModel(
            name='FirmDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.CharField(max_length=16)),
                ('region', models.CharField(blank=True, default='', max_length=64)),
                ('event_kind', models.CharField(max_length=64)),
                ('date', models.DateField(blank=True, null=True)),
                ('precision', models.CharField(blank=True, default='', max_length=32)),
                ('confidence', models.FloatField(default=0.0)),
                ('source_url', models.URLField(blank=True, default='', max_length=1024)),
                ('found_on', models.DateTimeField(blank=True, null=True)),
                ('history', models.JSONField(blank=True, default=list)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firm_dates', to='directory.firm')),
            ],
            options={
                'db_table': 'firm_dates',
                'ordering': ['firm_id', 'cycle', 'event_kind'],
                'constraints': [models.UniqueConstraint(fields=('firm', 'cycle', 'region', 'event_kind'), name='uniq_firm_dates_firm_cycle_region_event')],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('bucket', models.CharField(blank=True, default='', max_length=64)),
                ('region', models.CharField(blank=True, default='', max_length=64)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('cohort', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('deadline_precision', models.CharField(blank=True, default='', max_length=32)),
                ('confidence', models.FloatField(default=0.0)),
                ('sponsorship', models.CharField(blank=True, default='unknown', max_length=32)),
                ('url', models.URLField(max_length=1024)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='directory.firm')),
            ],
            options={
                'db_table': 'opportunities',
                'ordering': ['-first_seen'],
                'constraints': [models.UniqueConstraint(fields=('firm', 'url'), name='uniq_opportunity_firm_url')],
            },
        ),
    ]
