# Generated by Django 5.2.16 on 2026-07-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='class_year',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
