# Generated by Django 5.2.16 on 2026-08-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_backfill_class_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='posted_at',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='raw',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
