# Generated by Django 5.2.16 on 2026-08-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_opportunity_raw_and_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='firm-logos/'),
        ),
    ]
