# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_opportunity_raw_and_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='deadline_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
