# Generated by Django 5.2.16 on 2026-08-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_firm_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='class_year_derived',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
