# Generated by Django 5.2.16 on 2026-08-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_opportunity_class_year_derived'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='deadline_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
