# Generated by Django 5.2.16 on 2026-08-18 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_opportunity_deadline_checked_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=32)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('stage', models.CharField(max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('observed_at', models.DateTimeField()),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='directory.opportunity')),
            ],
            options={
                'db_table': 'opportunity_changes',
                'ordering': ['-observed_at', '-id'],
                'indexes': [models.Index(fields=['opportunity', '-observed_at'], name='opp_change_opp_seen_idx'), models.Index(fields=['field', '-observed_at'], name='opp_change_field_seen_idx'), models.Index(fields=['observed_at'], name='opp_change_seen_idx')],
            },
        ),
    ]
