# Generated by Django 5.2.16 on 2026-08-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_opportunitychange'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['status', 'bucket'], name='idx_opp_status_bucket'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(condition=models.Q(('status', 'open')), fields=['bucket', 'deadline', 'first_seen'], name='idx_opp_open_campus'),
        ),
    ]
