# Generated by Django 5.2.16 on 2026-08-26 06:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_opportunity_idx_opp_status_bucket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text="Domains associated with this firm — both the MAIL domains its people send from (e.g. 'gs.com', used to match an email address to the firm) and the CAREER-SITE hosts its postings live on (e.g. 'careers.bcg.com'). Nobody sends mail from a career site: adding one here will not make an address resolve.", size=None),
        ),
    ]
