# Generated by Django 5.2.16 on 2026-08-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_firmdate_firm_dates_confidence_in_range_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='firmdate',
            constraint=models.CheckConstraint(condition=models.Q(('precision__in', ('', 'day', 'month', 'estimated'))), name='firm_dates_precision_vocabulary'),
        ),
    ]
