# Generated by Django 5.2.16 on 2026-08-30 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0014_firmdate_cycle_vocabulary_and_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmCycleObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, default='', max_length=64)),
                ('opened_count', models.PositiveIntegerField(default=0)),
                ('open_window_first', models.DateField(blank=True, null=True)),
                ('open_window_last', models.DateField(blank=True, null=True)),
                ('closed_count', models.PositiveIntegerField(default=0)),
                ('close_window_first', models.DateField(blank=True, null=True)),
                ('close_window_last', models.DateField(blank=True, null=True)),
                ('excluded_suspect_closes', models.PositiveIntegerField(default=0)),
                ('currently_open_count', models.PositiveIntegerField(default=0)),
                ('onboarded_at', models.DateField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_observations', to='directory.firm')),
            ],
            options={
                'db_table': 'firm_cycle_observations',
                'ordering': ['firm_id', 'region'],
                'constraints': [models.UniqueConstraint(fields=('firm', 'region'), name='uniq_firm_cycle_observation_firm_region')],
            },
        ),
    ]
