# Generated by Django 5.2.16 on 2026-09-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0015_firmcycleobservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='recruiting_style',
            field=models.CharField(blank=True, choices=[('campus', 'Campus: networking moves the process'), ('assessment', 'Assessment: test-gated, a chat does not')], default='campus', help_text="How the firm hires. 'campus' (default): coffee chats and referrals move the process. 'assessment': the process is a test or competition and networking does not move it.", max_length=16),
        ),
    ]
