# Generated by Django 5.2.16 on 2026-08-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailconnection',
            name='backfill_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmailconnection',
            name='backfill_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='gmailconnection',
            name='backfill_status',
            field=models.CharField(choices=[('none', 'Not started'), ('pending', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed — will retry')], default='none', max_length=16),
        ),
    ]
