# Generated by Django 5.2.16 on 2026-08-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0002_gmailconnection_backfill_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailconnection',
            name='rescan_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmailconnection',
            name='rescan_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmailconnection',
            name='rescan_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='gmailconnection',
            name='rescan_status',
            field=models.CharField(choices=[('none', 'Never run'), ('pending', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed — will retry')], default='none', max_length=16),
        ),
    ]
