# Generated by Django 5.2.16 on 2026-08-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0003_gmailconnection_rescan_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailconnection',
            name='backfill_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
