# Generated by Django 5.2.16 on 2026-08-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0004_gmailconnection_backfill_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailconnection',
            name='rescan_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
