# Generated by Django 5.2.16 on 2026-08-21 18:40

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0005_gmailconnection_rescan_started_at'),
        ('crm', '0011_contact_recruiting_contact'),
        ('directory', '0009_opportunity_idx_opp_status_bucket_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('role_hint', models.CharField(blank=True, default='', max_length=255)),
                ('recruiting_hint', models.BooleanField(default=False)),
                ('evidence', models.CharField(blank=True, default='', max_length=300)),
                ('evidence_kind', models.CharField(default='reply_received', max_length=32)),
                ('thread_id', models.CharField(blank=True, default='', max_length=128)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], default='pending', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='crm.contact')),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_proposals', to='directory.firm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contact_proposals',
                'ordering': ['created'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('user', 'email'), name='uniq_contact_proposal_user_email')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
