# Generated by Django 5.2.16 on 2026-08-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0006_contactproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactproposal',
            name='thread_subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactproposal',
            name='threaded_reply',
            field=models.BooleanField(default=False),
        ),
    ]
