# Generated by Django 5.2.16 on 2026-08-23 21:12

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0006_contactproposal'),
        ('directory', '0009_opportunity_idx_opp_status_bucket_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_text', models.CharField(blank=True, default='', max_length=255)),
                ('event_type', models.CharField(choices=[('applied', 'Application received'), ('assessment', 'Online assessment invite'), ('video_interview', 'Video interview invite'), ('interview', 'Interview scheduling'), ('rejected', 'Decision received'), ('offer', 'Offer')], max_length=32)),
                ('target_status', models.CharField(max_length=32)),
                ('evidence', models.CharField(blank=True, default='', max_length=300)),
                ('detected_by', models.CharField(default='rules', max_length=16)),
                ('match_reason', models.CharField(blank=True, default='', max_length=200)),
                ('thread_id', models.CharField(blank=True, default='', max_length=128)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], default='pending', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_events', to='directory.firm')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_events', to='directory.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application_events',
                'ordering': ['created'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('user', 'opportunity', 'event_type'), name='uniq_application_event_user_opp_kind')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
