# Generated by Django 5.2.16 on 2026-08-23 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0007_applicationevent'),
        ('capture', '0007_contactproposal_thread_subject_and_more'),
    ]

    operations = [
    ]
