# Generated by Django 5.2.16 on 2026-08-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0008_merge_20260823_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationevent',
            name='due_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationevent',
            name='event_type',
            field=models.CharField(choices=[('applied', 'Application received'), ('advanced', 'Advanced in the process'), ('assessment', 'Online assessment invite'), ('video_interview', 'Video interview invite'), ('interview', 'Interview scheduling'), ('rejected', 'Decision received'), ('offer', 'Offer')], max_length=32),
        ),
    ]
