# Generated by Django 5.2.16 on 2026-08-27 17:31

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0009_applicationevent_due_on'),
        ('crm', '0015_contact_recruitment_related'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('departed', 'No longer at the firm'), ('referral', 'Referred you to someone'), ('out_of_office', 'Out of office'), ('address_change', 'New email address'), ('routing_address', 'Alternate routing address'), ('review', 'Auto-reply to review')], max_length=32)),
                ('about_email', models.EmailField(max_length=254)),
                ('about_name', models.CharField(blank=True, default='', max_length=255)),
                ('new_email', models.EmailField(blank=True, default='', max_length=254)),
                ('new_name', models.CharField(blank=True, default='', max_length=255)),
                ('return_on', models.DateField(blank=True, null=True)),
                ('quote', models.CharField(blank=True, default='', max_length=500)),
                ('subject', models.CharField(blank=True, default='', max_length=300)),
                ('detected_by', models.CharField(default='rules', max_length=16)),
                ('thread_id', models.CharField(blank=True, default='', max_length=128)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('undone', 'Undone'), ('dismissed', 'Dismissed')], default='pending', max_length=16)),
                ('action_note', models.CharField(blank=True, default='', max_length=300)),
                ('prior_email', models.EmailField(blank=True, default='', max_length=254)),
                ('snoozed_to', models.DateTimeField(blank=True, null=True)),
                ('note_line', models.CharField(blank=True, default='', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_facts', to='crm.contact')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_facts', to='capture.contactproposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mail_facts',
                'ordering': ['created'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('user', 'about_email', 'kind'), name='uniq_mail_fact_user_about_kind')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
