# Generated by Django 5.2.16 on 2026-08-27 17:25

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0009_applicationevent_due_on'),
        ('crm', '0015_contact_recruitment_related'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutopilotRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Deciding'), ('reviewed', 'Reviewed — waiting for your tap'), ('applied', 'Applied'), ('failed', 'Failed')], default='running', max_length=16)),
                ('source_label', models.CharField(blank=True, default='', max_length=200)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('accepts', models.IntegerField(default=0)),
                ('escalations', models.IntegerField(default=0)),
                ('skips', models.IntegerField(default=0)),
                ('deferred', models.IntegerField(default=0)),
                ('llm_calls', models.IntegerField(default=0)),
                ('credits_spent', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'autopilot_runs',
                'ordering': ['-created'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AutopilotDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('accept', 'Add it'), ('escalate', 'Needs you')], max_length=16)),
                ('confidence', models.FloatField(default=0.0)),
                ('quote', models.CharField(blank=True, default='', max_length=500)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('detected_by', models.CharField(default='ai', max_length=32)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('applied', 'Applied'), ('undone', 'Undone')], default='proposed', max_length=16)),
                ('overridden', models.BooleanField(default=False)),
                ('created_contact', models.BooleanField(default=False)),
                ('touch_id', models.IntegerField(blank=True, null=True)),
                ('undo_state', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('app_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autopilot_decisions', to='capture.applicationevent')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autopilot_decisions', to='crm.contact')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autopilot_decisions', to='capture.contactproposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='capture.autopilotrun')),
            ],
            options={
                'db_table': 'autopilot_decisions',
                'ordering': ['created'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('app_event__isnull', True), ('proposal__isnull', False)), models.Q(('app_event__isnull', False), ('proposal__isnull', True)), _connector='OR'), name='autopilot_decision_one_subject')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
