# Generated by Django 5.2.16 on 2026-08-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0010_autopilotrun_autopilotdecision'),
        ('capture', '0010_mailfact'),
    ]

    operations = [
    ]
