# Generated by Django 5.2.16 on 2026-08-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0011_merge_20260827_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailfact',
            name='prior_snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
