# Generated by Django 5.2.16 on 2026-08-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0012_mailfact_prior_snoozed_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopilotdecision',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('applied', 'Applied'), ('undone', 'Undone'), ('superseded', 'Superseded')], default='proposed', max_length=16),
        ),
    ]
