# Generated by Django 5.2.16 on 2026-09-02 16:38
#
# Choices only. `MailFact.kind` gains "bounced" — the structured record a
# permanent delivery failure never left (see the model's own note). No column
# changes, no rows are touched, and no existing row's kind means anything
# different than it did before this ran.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0015_autopilotrun_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailfact',
            name='kind',
            field=models.CharField(choices=[('departed', 'No longer at the firm'), ('referral', 'Referred you to someone'), ('out_of_office', 'Out of office'), ('address_change', 'New email address'), ('routing_address', 'Alternate routing address'), ('bounced', 'Address bounced'), ('review', 'Auto-reply to review')], max_length=32),
        ),
    ]
