# Generated by Django 5.2.16 on 2026-08-05 03:35

from django.db import migrations, models


def respect_existing_choices(apps, schema_editor):
    """Auto-detection is the new default, but only for accounts that never
    made a choice.

    The field default is True, which is right for every new account and for
    everyone still on the blank "Coverage uses UTC days" setting — those users
    never picked anything, and a zone that follows their computer is strictly
    better than a UTC day that rolls over at 8am in Hong Kong.

    It is WRONG for anyone with a stored zone: they went to Settings and
    chose. Turning auto on for them would let the next page load quietly
    overrule that choice, which is the behaviour this whole flag exists to
    prevent. So they start with auto off and keep exactly what they set.
    """
    User = apps.get_model("accounts", "user")
    User.objects.exclude(timezone="").update(timezone_auto=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone_auto',
            field=models.BooleanField(default=True),
        ),
        # Reverse is a no-op: dropping the column loses the distinction
        # anyway, and there is nothing to restore it from.
        migrations.RunPython(respect_existing_choices, migrations.RunPython.noop),
    ]
