# Generated by Django 5.2.16 on 2026-08-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_timezone_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calendar_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
