# Generated by Django 5.2.16 on 2026-08-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weekly_digest_opt_out',
            field=models.BooleanField(default=False),
        ),
    ]
