# Generated by Django 5.2.16 on 2026-08-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_target_cycles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='capture_slug',
        ),
    ]
