# Generated by Django 5.2.16 on 2026-08-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_user_capture_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pro_trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pro_trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
