# Generated by Django 5.2.16 on 2026-08-26 06:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_pro_trial_ends_at_user_pro_trial_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None),
        ),
    ]
