# Generated by Django 5.2.16 on 2026-07-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useropportunity',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
