# Generated by Django 5.2.16 on 2026-08-19 06:35

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('kind', models.CharField(choices=[('grant', 'Monthly grant'), ('spend_chat', 'Chat message'), ('spend_rescan', 'Rescan residue classification'), ('adjust', 'Admin adjustment')], max_length=32)),
                ('period', models.CharField(blank=True, default='', max_length=7)),
                ('props', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_ledger',
                'ordering': ['-created'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['user', 'created'], name='credit_ledg_user_id_92099a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'grant')), fields=('user', 'period'), name='uniq_monthly_grant')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
