# Generated by Django 5.2.16 on 2026-08-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedStripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='creditledger',
            name='kind',
            field=models.CharField(choices=[('grant', 'Monthly grant'), ('spend_chat', 'Chat message'), ('spend_rescan', 'Rescan residue classification'), ('adjust', 'Admin adjustment'), ('purchase', 'Credit top-up purchase')], max_length=32),
        ),
    ]
