# Generated by Django 5.2.16 on 2026-08-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_processedstripeevent_alter_creditledger_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditledger',
            name='kind',
            field=models.CharField(choices=[('grant', 'Monthly grant'), ('spend_chat', 'Chat message'), ('spend_rescan', 'Rescan residue classification'), ('adjust', 'Admin adjustment'), ('purchase', 'Credit top-up purchase'), ('refund', 'Refund of a failed turn')], max_length=32),
        ),
    ]
