# Generated by Django 5.2.16 on 2026-08-19 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_creditledger_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditledger',
            name='kind',
            field=models.CharField(choices=[('grant', 'Monthly grant'), ('spend_chat', 'Chat message'), ('spend_rescan', 'Rescan residue classification'), ('adjust', 'Admin adjustment'), ('purchase', 'Credit top-up purchase'), ('refund', 'Refund of a failed turn'), ('upgrade', 'Mid-period plan upgrade top-up')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='creditledger',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'upgrade')), fields=('user', 'period'), name='uniq_monthly_upgrade'),
        ),
    ]
