# Generated by Django 5.2.16 on 2026-08-19 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_creditledger_kind_and_more'),
        ('billing', '0004_prowaitlist'),
    ]

    operations = [
    ]
