# Generated by Django 5.2.16 on 2026-08-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_creditledger_kind'),
        ('billing', '0005_merge_20260819_1813'),
    ]

    operations = [
    ]
