# Generated by Django 5.2.16 on 2026-08-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_merge_20260819_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditledger',
            name='kind',
            field=models.CharField(choices=[('grant', 'Monthly grant'), ('spend_chat', 'Chat message'), ('spend_rescan', 'Rescan residue classification'), ('spend_brief', 'Coffee-chat brief'), ('adjust', 'Admin adjustment'), ('purchase', 'Credit top-up purchase'), ('refund', 'Refund of a failed turn'), ('upgrade', 'Mid-period plan upgrade top-up')], max_length=32),
        ),
    ]
