# Firm slug -> the firm's own front-door domain. Hand-written; every entry is
# probed for a real logo before it is committed to the database.
DOMAINS = {
    "point72": "point72.com", "janestreet": "janestreet.com",
    "optiver": "optiver.com", "drw": "drw.com", "imc": "imc.com",
    "jump": "jumptrading.com", "hrt": "hudsonrivertrading.com",
    "mizuho": "mizuhogroup.com", "troweprice": "troweprice.com",
    "oliverwyman": "oliverwyman.com", "pimco": "pimco.com",
    "ares": "aresmgmt.com", "raymondjames": "raymondjames.com",
    "capitalgroup": "capitalgroup.com", "vanguard": "vanguard.com",
    "brookfield": "brookfield.com", "carlyle": "carlyle.com",
    "pwc": "pwc.com", "franklintempleton": "franklintempleton.com",
    "fidelityintl": "fidelityinternational.com",
    "alliancebernstein": "alliancebernstein.com", "invesco": "invesco.com",
    "neubergerberman": "nb.com", "oaktree": "oaktreecapital.com",
    "blueowl": "blueowl.com", "apollo": "apollo.com", "virtu": "virtu.com",
    "williamblair": "williamblair.com", "flowtraders": "flowtraders.com",
    "golub": "golubcapital.com", "akuna": "akunacapital.com",
    "baincapital": "baincapital.com", "baird": "rwbaird.com",
    "sixthstreet": "sixthstreet.com", "pipersandler": "pipersandler.com",
    "fiverings": "fiveringsllc.com", "brattle": "brattle.com",
    "generalatlantic": "generalatlantic.com", "schroders": "schroders.com",
    "tpg": "tpg.com", "eqt": "eqtgroup.com", "statestreet": "statestreet.com",
    "wellington": "wellington.com", "solomonpartners": "solomonpartners.com",
    "mangroup": "man.com",
    # Firms that HAVE a domain but whose logo fetch failed — better front doors.
    "blackrock": "blackrock.com", "clsa": "clsa.com", "cicc": "cicc.com",
    "boci": "bocigroup.com", "guggenheim": "guggenheimpartners.com",
    "huatai": "htsc.com.cn", "guotaijunan": "gtjai.com",
}
