# Generated by Django 5.2.16 on 2026-07-23 06:59

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('provider_ref', models.CharField(max_length=255)),
                ('direction', models.CharField(blank=True, choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], default='', max_length=16)),
                ('counterparty_email', models.EmailField(blank=True, default='', max_length=254)),
                ('counterparty_name', models.CharField(blank=True, default='', max_length=255)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('raw_ref', models.CharField(blank=True, default='', max_length=512)),
                ('signals', models.JSONField(blank=True, default=dict)),
                ('extraction_version', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('needs_review', 'Needs review'), ('ignored', 'Ignored')], default='pending', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'capture_events',
                'ordering': ['-received_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('firm_text', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('linkedin', models.URLField(blank=True, default='', max_length=512)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('warmth', models.CharField(default='cold', max_length=32)),
                ('thread_state', models.CharField(default='no_reply', max_length=32)),
                ('angle', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('school_affiliation', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('email_pattern_recorded', models.BooleanField(default=False)),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='directory.firm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['-created'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('why', models.TextField(blank=True, default='')),
                ('due', models.DateField(blank=True, null=True)),
                ('kind', models.CharField(blank=True, default='', max_length=64)),
                ('source_key', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='open', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='directory.firm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['due', '-created'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Touch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('channel', models.CharField(blank=True, max_length=32, null=True)),
                ('kind', models.CharField(max_length=64)),
                ('note', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('capture', 'Capture'), ('import', 'Import')], default='manual', max_length=16)),
                ('capture_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touches', to='crm.captureevent')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touches', to='crm.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'touches',
                'ordering': ['-ts'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.SmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.firm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_firms',
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='captureevent',
            constraint=models.UniqueConstraint(fields=('user', 'provider', 'provider_ref'), name='uniq_capture_events_user_provider_ref'),
        ),
        migrations.AddConstraint(
            model_name='userfirm',
            constraint=models.UniqueConstraint(fields=('user', 'firm'), name='uniq_user_firms_user_firm'),
        ),
    ]
