# Generated by Django 5.2.16 on 2026-07-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='contact',
            name='school',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
