# Generated by Django 5.2.16 on 2026-07-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_contact_gender_contact_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
