# Generated by Django 5.2.16 on 2026-07-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_contact_snoozed_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='opener',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='region',
            field=models.CharField(blank=True, choices=[('us', 'United States'), ('hk', 'Hong Kong')], default='', max_length=8),
        ),
    ]
