# Generated by Django 5.2.16 on 2026-07-25 04:29

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_backfill_contact_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatDebrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learned', models.TextField(blank=True, default='')),
                ('intro_name', models.CharField(blank=True, default='', max_length=255)),
                ('intro_email', models.EmailField(blank=True, default='', max_length=254)),
                ('tracked_date', models.DateField(blank=True, null=True)),
                ('date_note', models.CharField(blank=True, default='', max_length=255)),
                ('advocate_answer', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], default='', max_length=16)),
                ('promoted', models.BooleanField(default=False)),
                ('dismissed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debriefs', to='crm.contact')),
                ('date_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.task')),
                ('intro_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_by_debriefs', to='crm.contact')),
                ('intro_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.task')),
                ('touch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debriefs', to='crm.touch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_debriefs',
                'ordering': ['-created'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('user', 'touch'), name='uniq_chat_debriefs_user_touch')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
