# Generated by Django 5.2.16 on 2026-08-04 16:36

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_chatdebrief'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('chat', 'Coffee chat'), ('event', 'Event')], default='event', max_length=16)),
                ('source', models.CharField(choices=[('manual', 'Added by you'), ('capture', 'From your mailbox')], default='manual', max_length=16)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('thread_id', models.CharField(blank=True, default='', max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='crm.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calendar_events',
                'ordering': ['starts_at', 'id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['user', 'starts_at'], name='calendar_ev_user_id_8e2a35_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('thread_id', ''), _negated=True), fields=('user', 'thread_id'), name='uniq_calendar_event_user_thread')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
