# Generated by Django 5.2.16 on 2026-08-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_calendarevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touch',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('capture', 'Capture'), ('import', 'Import'), ('assistant', 'Assistant')], default='manual', max_length=16),
        ),
    ]
