# Generated by Django 5.2.16 on 2026-08-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_touch_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='ai_summary_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
