# Generated by Django 5.2.16 on 2026-08-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_contact_ai_summary_contact_ai_summary_generated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touch',
            name='capture_event',
        ),
        migrations.DeleteModel(
            name='CaptureEvent',
        ),
    ]
