# Generated by Django 5.2.16 on 2026-08-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_remove_touch_capture_event_delete_captureevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='recruiting_contact',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
