# Generated by Django 5.2.16 on 2026-08-21 18:18

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_contact_recruiting_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='campaign_exempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='touch',
            name='subject',
            field=models.CharField(blank=True, db_default='', default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('kind', models.CharField(choices=[('unclassified', 'Not answered yet'), ('recruiting', 'My own recruiting'), ('other', 'Something else I do')], default='unclassified', max_length=16)),
                ('classified_at', models.DateTimeField(blank=True, null=True)),
                ('first_sent', models.DateTimeField()),
                ('last_sent', models.DateTimeField()),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-last_sent', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CampaignContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originates', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='crm.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_memberships', to='crm.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaign_contacts',
                'ordering': ['campaign_id', 'contact_id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(fields=('user', 'signature'), name='uniq_campaigns_user_signature'),
        ),
        migrations.AddIndex(
            model_name='campaigncontact',
            index=models.Index(fields=['user', 'contact'], name='campaign_co_user_id_28dbd5_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaigncontact',
            constraint=models.UniqueConstraint(fields=('user', 'campaign', 'contact'), name='uniq_campaign_contacts_user_campaign_contact'),
        ),
    ]
