# Generated by Django 5.2.16 on 2026-08-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_contact_campaign_exempt_touch_subject_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
