# Generated by Django 5.2.16 on 2026-08-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_contact_campaign_exempt_touch_subject_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='region',
            field=models.CharField(blank=True, choices=[('us', 'United States'), ('hk', 'Hong Kong'), ('other', 'Other countries')], default='', max_length=8),
        ),
    ]
