# Generated by Django 5.2.16 on 2026-08-26 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_contact_region'),
        ('crm', '0013_campaign_retired_at'),
    ]

    operations = [
    ]
