# Generated by Django 5.2.16 on 2026-08-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_merge_20260826_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='recruitment_related',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
