# Generated by Django 5.2.16 on 2026-08-27 22:42

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_contact_recruitment_related'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMerge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('merged', 'Merged'), ('undone', 'Undone'), ('rejected', 'Different people')], max_length=16)),
                ('moved_touch_ids', models.JSONField(blank=True, default=list)),
                ('field_changes', models.JSONField(blank=True, default=dict)),
                ('note_line', models.CharField(blank=True, default='', max_length=500)),
                ('duplicate_was_archived', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('duplicate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merges_folded', to='crm.contact')),
                ('primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merges_kept', to='crm.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contact_merges',
                'ordering': ['-created', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['user', 'status'], name='contact_mer_user_id_f2c695_idx')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
