# Generated by Django 5.2.16 on 2026-08-27 23:56

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_contact_region_source'),
        ('directory', '0011_firm_slug_not_blank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_kind', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.firm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'play_dismissals',
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('user', 'firm', 'event_kind', 'date'), name='uniq_play_dismissals_fact')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
