# Generated by Django 5.2.16 on 2026-08-28 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_benchdismissal'),
        ('crm', '0018_playdismissal'),
    ]

    operations = [
    ]
