# Generated by Django 5.2.16 on 2026-08-28 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_calendarevent_ics_uid_calendarevent_invite_sent_at_and_more'),
        ('crm', '0019_merge_0018_benchdismissal_0018_playdismissal'),
    ]

    operations = [
    ]
