# Generated by Django 5.2.16 on 2026-08-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_merge_20260828_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
