# Generated by Django 5.2.16 on 2026-09-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_alter_touch_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
