# Generated by Django 5.2.16 on 2026-09-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_contact_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='time_confidence',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='time_evidence',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
