# Generated by Django 5.2.16 on 2026-09-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_calendarevent_google_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='region_source',
            field=models.CharField(blank=True, choices=[('user', 'Set by you'), ('declared', 'From your target regions'), ('firm', "From the firm's markets"), ('web', 'From their public profile'), ('reply', 'They told you in an email')], default='', max_length=16),
        ),
    ]
