# Generated by Django 5.2.16 on 2026-08-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_memory_and_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybrief',
            name='contact_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
